[package]
name = "workers-core-rust"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = { version = "0.7.0" }

[[bench]]
name = "one_to_one_sequencer_item_single"
harness = false

[[bench]]
name = "one_to_one_sequencer_item_batch"
harness = false